export const attendeeTypes = [
  [
    "Students / College Crowd",
    "Families",
    "Young Professionals",
    "Tourists",
    "Local Regulars",
    "High-Income Shoppers",
    "Budget-Conscious Shoppers",
    "Trendsetters / Influencers",
    "Art Collectors / Design Enthusiasts",
    "Foodies / Culinary Explorers",
    "Health & Wellness Enthusiasts",
    "Eco-Conscious / Sustainable Shoppers",
    "Spiritual / Holistic Audiences",
    "Fashion-Focused Customers",
    "Parents & Kids",
    "Pet Owners",
    "BIPOC Communities",
    "Black / African American Communities",
    "Latinx / Hispanic Communities",
    "Asian American & Pacific Islander (AAPI) Communities",
    "Native American / Indigenous Communities",
    "Middle Eastern & North African (MENA) Communities",
    "LGBTQ+ Community",
    "Women-Centered Audiences",
    "Men-Centered Audiences",
    "Nonbinary / Gender Diverse Audiences",
    "Mothers",
    "Fathers",
    "Single Parents",
    "Elderly / Retired Shoppers",
    "Remote Workers / Digital Nomads",
    "Festival-Goers / Music Lovers",
    "Travelers & Expats",
    "Gift Shoppers / Holiday Buyers",
    "Small Business Supporters",
    "Craft / DIY Enthusiasts",
    "Outdoor Adventurers",
    "Home & Garden Enthusiasts",
    "Tech Enthusiasts & Early Adopters",
    "Parents-to-Be / New Parents",
    "Cultural Enthusiasts",
    "Sports Fans",
    "Collectors (Vintage, Comics, Antiques)",
    "Social Justice Advocates",
    "Faith-Based Audiences (e.g., Christian, Muslim, Jewish Events)",
    "Immigrant Communities",
    "Veterans / Military Families",
    "Disability Community",
  ],
];
