export const categories = [  
  "Latin American (Mexican, Caribbean, Peruvian, Brazilian)",  
  "Fusion (Latin-Asian, Tex-Mex, Mediterranean-Latin)",  
  "Street Food & Casual Bites",  
  "Fine Dining & Gourmet",  
  "Plant-Based & Vegan Cuisine",  
  "Pop-Up Experiences",  
  "Themed Pop-Up Dinners",  
  "Chef Collaborations",  
  "Seasonal/Flash Pop-Ups",  
  "Food Trucks & Mobile Kitchens",  
  "Tasting Menus & Chef’s Table",  
  "Brunch/Lunch vs. Dinner Events",  
  "Latin American Heritage (Dia de los Muertos, Carnaval-themed)",  
  "Regional Specialties (Oaxacan, Andean, Coastal Caribbean)",  
  "Immersive Cultural Experiences (Live Music, Dance, Art)",  
  "Gluten-Free & Allergy-Friendly",  
  "Vegetarian & Vegan Options",  
  "Low-Carb/Keto-Friendly",  
  "Family-Style Sharing Plates",  
  "Tapas/Small Plates",  
  "Interactive Cooking Stations",  
  "Grab-and-Go (Food Markets, Festivals)",  
  "Farm-to-Table/Locally Sourced",  
  "Zero-Waste Initiatives",  
  "Ethical Sourcing (Fair Trade, Organic)",  
  "Holiday Menus (Cinco de Mayo, Christmas Tamales)",  
  "Summer BBQ/Tropical Themes",  
  "Winter Comfort Food",  
  "Latin Cocktails (Margaritas, Pisco Sours)",  
  "Craft Beer/Wine Pairings",  
  "Non-Alcoholic (Aguas Frescas, Coffee Blends)"  
];  
