import type { Metadata } from "next";
import Header from "@/components/Header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BusinessProfileProvider } from '../context/BusinessProfileContext';
import { BusinessAdjectiveProvider } from '../context/BusinessAdjectiveContext';
import { BusinessPastPopupProvider } from '../context/BusinessPastPopupContext';
import { BusinessLogoProvider } from '../context/BusinessLogoContext';
import { BusinessBudgetProvider } from "@/context/BusinessBudgetContext";
import { BusinessCustomerProvider } from "@/context/BusinessCustomerContext";
import { BusinessScheduleProvider } from "@/context/BusinessScheduleContext";
import { BusinessLocationProvider } from "@/context/BusinessLocationContext";
import { UserProvider } from '../context/UserContext';
import { HostProvider } from '../context/HostContext';
import { ApplicationProfileProvider } from '../context/ApplicationProfileContext'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider><HostProvider>
        <Header />
        <main>
          <ApplicationProfileProvider>
          <BusinessProfileProvider>
            <BusinessAdjectiveProvider>
              <BusinessLogoProvider>
                <BusinessPastPopupProvider>
                  <BusinessBudgetProvider>
                    <BusinessCustomerProvider>
                      <BusinessScheduleProvider>
                        <BusinessLocationProvider>
                          {children}
                        </BusinessLocationProvider>
                      </BusinessScheduleProvider>
                    </BusinessCustomerProvider>
                  </BusinessBudgetProvider>
                </BusinessPastPopupProvider>
              </BusinessLogoProvider>
            </BusinessAdjectiveProvider>
          </BusinessProfileProvider>
          </ApplicationProfileProvider>
        </main>
        </HostProvider></UserProvider>
      </body>
    </html>
  );
}



